version: "2.1"
services:
  packet_forwarder:
    restart: always
    image: ghcr.io/heliumdiy/sx1302_hal:latest
    privileged: true
    environment:
      - VENDOR=rakv2
      - REGION=US915
      - CONCENTRATOR_INTERFACE=17
      - CONCENTRATOR_MODEL=sx1302
      - CONFIG_FILE=/opt/packet_forwarder/configs/local_conf.json
  helium_miner:
    restart: always
    image: quay.io/team-helium/miner:latest-arm64
    privileged: true
    ports:
      - "44158:44158/tcp"
      - "1680:1680/udp"
    volumes:
      - 'miner-data:/var/data'
      - 'miner-log:/var/log/miner'
volumes:
  miner-data:
  miner-log:
