version: "2.1"
services:
  loragtwpktfwd:
    restart: always
    image: docker pull ghcr.io/heliumdiy/sx1302_hal:latest
    privileged: true
  helium_miner:
    restart: always
    image: quay.io/team-helium/miner:latest-arm64
    ports:
      - "44158:44158/tcp"
      - "1680:1680/udp"
    volumes:
      - 'miner-data:/var/data'
      - 'miner-log:/var/log/miner'

volumes:
  miner-data:
  miner-log:
